version: "3.9"

services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql+asyncpg://mazpen:mazpen@host.docker.internal:5433/mazpen_db
      SYNC_DATABASE_URL: postgresql+psycopg2://mazpen:mazpen@host.docker.internal:5433/mazpen_db
      REDIS_URL: redis://host.docker.internal:6379
      SECRET_KEY: change-this-to-a-very-long-random-secret-key-in-production
      DEBUG: "true"
    volumes:
      - .:/app
    command: sh -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  ui:
    build: ./uiApp
    ports:
      - "5173:5173"
    environment:
      VITE_API_URL: /api/v1
      API_PROXY_TARGET: http://api:8000
    depends_on:
      - api
    volumes:
      - ./uiApp:/app
      - ui_node_modules:/app/node_modules

volumes:
  ui_node_modules:
