import { createContext, useContext, useState, useEffect, ReactNode, useCallback } from 'react';

export type Lang = 'en' | 'he';

interface LangContextType {
  lang: Lang;
  setLang: (lang: Lang) => void;
  t: (key: string) => string;
  dir: 'ltr' | 'rtl';
}

const LangContext = createContext<LangContextType>({
  lang: 'en',
  setLang: () => {},
  t: (key) => key,
  dir: 'ltr',
});

// ── Translations ────────────────────────────────────────
const translations: Record<Lang, Record<string, string>> = {
  en: {
    // Global / Layout
    'app.name': 'ECMS',
    'app.subtitle': 'Crisis Management',
    'app.alerts': 'Alerts',
    'nav.fieldReports': 'Field Reports',
    'nav.missions': 'Missions',
    'nav.gisDashboard': 'GIS Dashboard',
    'nav.visitors': 'Visitors',
    'nav.analytics': 'Analytics / Reports',
    'nav.settings': 'Settings',
    'user.role': 'Control Operator',

    // Field Reports
    'fieldReports.title': 'Field Measurement Reporting',
    'fieldReports.subtitle': 'Submit and manage environmental measurements',
    'fieldReports.online': 'Online – All data synced',
    'fieldReports.lastSync': 'Last sync: 2 min ago',
    'fieldReports.newReport': 'New Report',
    'fieldReports.newReportDesc': 'Submit a field measurement',
    'fieldReports.myReports': 'My Reports',
    'fieldReports.myReportsDesc': 'View submitted reports',
    'fieldReports.pending': 'Pending',
    'fieldReports.verified': 'Verified',
    'fieldReports.flagged': 'Flagged',
    'fieldReports.recentActivity': 'Recent Activity',

    // New Measurement
    'newMeasurement.title': 'New Measurement Report',
    'newMeasurement.subtitle': 'Fill in the details below',
    'newMeasurement.online': 'Online – will sync immediately',
    'newMeasurement.gpsLocation': 'GPS Location (auto-captured)',
    'newMeasurement.timestamp': 'Timestamp',
    'newMeasurement.team': 'Team',
    'newMeasurement.type': 'Measurement Type',
    'newMeasurement.value': 'Measurement Value',
    'newMeasurement.notes': 'Notes',
    'newMeasurement.notesPlaceholder': 'Additional observations, conditions, etc.',
    'newMeasurement.photo': 'Photo',
    'newMeasurement.photoPrompt': 'Tap to take photo or upload',
    'newMeasurement.submit': 'Submit Report',
    'newMeasurement.submitted': 'Report Submitted',
    'newMeasurement.submittedDesc': 'Your measurement has been recorded and is pending verification.',
    'newMeasurement.submitAnother': 'Submit Another',
    'newMeasurement.backToHub': 'Back to Hub',

    // My Reports
    'myReports.title': 'My Reports',
    'myReports.search': 'Search reports...',
    'myReports.allStatus': 'All Status',
    'myReports.allTypes': 'All Types',
    'myReports.noResults': 'No reports match your filters.',
    'myReports.reportId': 'Report ID',
    'myReports.severity': 'Severity',
    'myReports.location': 'Location',
    'myReports.editReport': 'Edit Report',

    // GIS Dashboard
    'gis.filters': 'Filters',
    'gis.alerts': 'Alerts',
    'gis.layers': 'Layers',
    'gis.measurements': 'Measurements',
    'gis.missions': 'Missions',
    'gis.visitors': 'Visitors',
    'gis.hazardZones': 'Hazard Zones',
    'gis.allTypes': 'All Types',
    'gis.allSeverities': 'All Severities',
    'gis.allTeams': 'All Teams',
    'gis.verifiedOnly': 'Verified only',
    'gis.safe': 'Safe',
    'gis.warning': 'Warning',
    'gis.danger': 'Danger',
    'gis.comment': 'Add a comment...',
    'gis.addComment': 'Add Comment',
    'gis.details': 'Details',
    'gis.commentsLog': 'Comments & Log',

    // Missions
    'missions.title': 'Missions',
    'missions.subtitle': 'Manage and track field operations',
    'missions.newMission': 'New Mission',
    'missions.mission': 'Mission',
    'missions.team': 'Team',
    'missions.status': 'Status',
    'missions.priority': 'Priority',
    'missions.createTitle': 'Create New Mission',
    'missions.name': 'Mission Name',
    'missions.namePlaceholder': 'e.g., Sector 5 Water Survey',
    'missions.assignTeam': 'Assign Team',
    'missions.objectives': 'Objectives',
    'missions.objectivesPlaceholder': 'Describe the mission objectives...',
    'missions.geoArea': 'Geographic Area',
    'missions.startDate': 'Start Date',
    'missions.cancel': 'Cancel',
    'missions.create': 'Create Mission',
    'missions.drawPromptEmpty': 'Click on the map to place polygon vertices',
    'missions.drawPromptFew': 'point(s) placed – need at least 3 for a polygon',
    'missions.drawPromptReady': 'points – polygon ready',
    'missions.undo': 'Undo',
    'missions.clear': 'Clear',

    // Visitors
    'visitors.title': 'Visitor Management',
    'visitors.subtitle': 'Track and manage population screening',
    'visitors.newIntake': 'New Intake',
    'visitors.total': 'Total',
    'visitors.cleared': 'Cleared',
    'visitors.observation': 'Observation',
    'visitors.flagged': 'Flagged',
    'visitors.search': 'Search by name, ID, or contact...',
    'visitors.allStatus': 'All Status',
    'visitors.underObservation': 'Under Observation',
    'visitors.name': 'Name',
    'visitors.idNumber': 'ID Number',
    'visitors.exposure': 'Exposure',
    'visitors.status': 'Status',
    'visitors.locations': 'locations',
    'visitors.view': 'View',

    // Visitor Intake
    'intake.title': 'Visitor Intake',
    'intake.subtitle': 'Register a new visitor for screening',
    'intake.personalDetails': 'Personal Details',
    'intake.fullName': 'Full Name',
    'intake.idNumber': 'ID Number',
    'intake.age': 'Age',
    'intake.contact': 'Contact',
    'intake.physicalMeasurements': 'Physical Measurements',
    'intake.exposureReading': 'Exposure Reading (μSv/h)',
    'intake.bloodPressure': 'Blood Pressure',
    'intake.heartRate': 'Heart Rate (bpm)',
    'intake.temperature': 'Temperature (°C)',
    'intake.visitedLocations': 'Visited Locations',
    'intake.locationPlaceholder': 'Location name or address',
    'intake.addLocation': 'Add Location',
    'intake.notes': 'Notes',
    'intake.notesPlaceholder': 'Additional observations, symptoms, medical history...',
    'intake.register': 'Register Visitor',
    'intake.registered': 'Visitor Registered',
    'intake.registeredDesc': 'The intake record has been saved successfully.',
    'intake.registerAnother': 'Register Another',
    'intake.viewAll': 'View All Visitors',
    'intake.bodyMeasurements': 'Body Measurements',
    'intake.zonePlaceholder': 'Body zone (e.g. Hands, Face)',
    'intake.addZone': 'Add Zone',
    'intake.removeZone': 'Remove Zone',
    'profile.bodyMeasurements': 'Body Measurements',

    // Visitor Profile
    'profile.notFound': 'Visitor Not Found',
    'profile.notFoundDesc': 'The visitor record could not be located.',
    'profile.backToVisitors': 'Back to Visitors',
    'profile.exportReport': 'Export Report',
    'profile.personalInfo': 'Personal Information',
    'profile.measurementsSummary': 'Measurements Summary',
    'profile.bloodPressure': 'Blood Pressure',
    'profile.heartRate': 'Heart Rate',
    'profile.temperature': 'Temperature',
    'profile.movementPath': 'Movement Path',
    'profile.start': 'Start',
    'profile.end': 'End',
    'profile.movementHistory': 'Movement History Timeline',

    // Analytics
    'analytics.title': 'Analytics & Reports',
    'analytics.subtitle': 'Operational overview and data analysis',
    'analytics.totalMeasurements': 'Total Measurements',
    'analytics.activeMissions': 'Active Missions',
    'analytics.visitorsTracked': 'Visitors Tracked',
    'analytics.teamsDeployed': 'Teams Deployed',
    'analytics.criticalAlerts': 'Critical Alerts',
    'analytics.today': 'today',
    'analytics.total': 'total',
    'analytics.severityDistribution': 'Severity Distribution',
    'analytics.measurementsByType': 'Measurements by Type',
    'analytics.readings': 'readings',
    'analytics.teamActivity': 'Team Activity',
    'analytics.members': 'Members',
    'analytics.reports': 'Reports',
    'analytics.lastReport': 'Last Report',

    // Settings
    'settings.title': 'Settings',
    'settings.subtitle': 'System preferences and configuration',
    'settings.appearance': 'Appearance',
    'settings.theme': 'Theme',
    'settings.themeDesc': 'Switch between light and dark mode',
    'settings.interfaceMode': 'Interface Mode',
    'settings.desktop': 'Desktop',
    'settings.desktopDesc': 'Full dashboard',
    'settings.tablet': 'Tablet',
    'settings.tabletDesc': 'Compact layout',
    'settings.mobile': 'Mobile',
    'settings.mobileDesc': 'Field mode',
    'settings.notifications': 'Notifications',
    'settings.thresholdBreach': 'Threshold breach alerts',
    'settings.thresholdBreachDesc': 'Notify when measurements exceed limits',
    'settings.teamSOS': 'Team SOS signals',
    'settings.teamSOSDesc': 'Immediate notification on distress signals',
    'settings.newMeasurementReports': 'New measurement reports',
    'settings.newMeasurementReportsDesc': 'Notify on incoming field reports',
    'settings.missionStatusChanges': 'Mission status changes',
    'settings.missionStatusChangesDesc': 'Updates when missions change state',
    'settings.visitorFlagging': 'Visitor flagging',
    'settings.visitorFlaggingDesc': 'Alert when visitors are flagged',
    'settings.userProfile': 'User Profile',
    'settings.fullName': 'Full Name',
    'settings.email': 'Email',
    'settings.systemInfo': 'System Information',
    'settings.version': 'Version',
    'settings.serverStatus': 'Server Status',
    'settings.operational': 'Operational',
    'settings.lastUpdate': 'Last Update',
    'settings.activeSessions': 'Active Sessions',
    'settings.dataRetention': 'Data Retention',
    'settings.days': 'days',
    'settings.mapProvider': 'Map Provider',

    // Common
    'common.actions': 'Actions',
    'common.notes': 'Notes',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.close': 'Close',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.back': 'Back',
    'common.status': 'Status',
    'common.alerts': 'Alerts',
  },

  he: {
    // Global / Layout
    'app.name': 'ECMS',
    'app.subtitle': 'ניהול משברים',
    'app.alerts': 'התראות',
    'nav.fieldReports': 'דוחות שטח',
    'nav.missions': 'משימות',
    'nav.gisDashboard': 'לוח מפות GIS',
    'nav.visitors': 'מבקרים',
    'nav.analytics': 'ניתוח ודוחות',
    'nav.settings': 'הגדרות',
    'user.role': 'מפעיל מוקד',

    // Field Reports
    'fieldReports.title': 'דיווח מדידות שטח',
    'fieldReports.subtitle': 'הגשה וניהול מדידות סביבתיות',
    'fieldReports.online': 'מחובר – כל הנתונים מסונכרנים',
    'fieldReports.lastSync': 'סנכרון אחרון: לפני 2 דקות',
    'fieldReports.newReport': 'דוח חדש',
    'fieldReports.newReportDesc': 'הגש מדידת שטח',
    'fieldReports.myReports': 'הדוחות שלי',
    'fieldReports.myReportsDesc': 'צפה בדוחות שהוגשו',
    'fieldReports.pending': 'ממתין',
    'fieldReports.verified': 'מאומת',
    'fieldReports.flagged': 'מסומן',
    'fieldReports.recentActivity': 'פעילות אחרונה',

    // New Measurement
    'newMeasurement.title': 'דוח מדידה חדש',
    'newMeasurement.subtitle': 'מלא את הפרטים למטה',
    'newMeasurement.online': 'מחובר – יסונכרן מיידית',
    'newMeasurement.gpsLocation': 'מיקום GPS (נלכד אוטומטית)',
    'newMeasurement.timestamp': 'חותמת זמן',
    'newMeasurement.team': 'צוות',
    'newMeasurement.type': 'סוג מדידה',
    'newMeasurement.value': 'ערך מדידה',
    'newMeasurement.notes': 'הערות',
    'newMeasurement.notesPlaceholder': 'תצפיות נוספות, תנאים וכו\'',
    'newMeasurement.photo': 'תמונה',
    'newMeasurement.photoPrompt': 'לחץ לצלם או להעלות',
    'newMeasurement.submit': 'שלח דוח',
    'newMeasurement.submitted': 'הדוח הוגש',
    'newMeasurement.submittedDesc': 'המדידה נרשמה וממתינה לאימות.',
    'newMeasurement.submitAnother': 'שלח עוד',
    'newMeasurement.backToHub': 'חזרה למרכז',

    // My Reports
    'myReports.title': 'הדוחות שלי',
    'myReports.search': 'חפש דוחות...',
    'myReports.allStatus': 'כל הסטטוסים',
    'myReports.allTypes': 'כל הסוגים',
    'myReports.noResults': 'אין דוחות התואמים את הסינון.',
    'myReports.reportId': 'מזהה דוח',
    'myReports.severity': 'חומרה',
    'myReports.location': 'מיקום',
    'myReports.editReport': 'ערוך דוח',

    // GIS Dashboard
    'gis.filters': 'מסננים',
    'gis.alerts': 'התראות',
    'gis.layers': 'שכבות',
    'gis.measurements': 'מדידות',
    'gis.missions': 'משימות',
    'gis.visitors': 'מבקרים',
    'gis.hazardZones': 'אזורי סכנה',
    'gis.allTypes': 'כל הסוגים',
    'gis.allSeverities': 'כל רמות החומרה',
    'gis.allTeams': 'כל הצוותות',
    'gis.verifiedOnly': 'מאומתים בלבד',
    'gis.safe': 'בטוח',
    'gis.warning': 'אזהרה',
    'gis.danger': 'סכנה',
    'gis.comment': 'הוסף הערה...',
    'gis.addComment': 'הוסף הערה',
    'gis.details': 'פרטים',
    'gis.commentsLog': 'הערות ויומן',

    // Missions
    'missions.title': 'משימות',
    'missions.subtitle': 'ניהול ומעקב אחר פעולות שטח',
    'missions.newMission': 'משימה חדשה',
    'missions.mission': 'משימה',
    'missions.team': 'צוות',
    'missions.status': 'סטטוס',
    'missions.priority': 'עדיפות',
    'missions.createTitle': 'יצירת משימה חדשה',
    'missions.name': 'שם משימה',
    'missions.namePlaceholder': 'לדוגמה, סקר מים סקטור 5',
    'missions.assignTeam': 'שיבוץ צוות',
    'missions.objectives': 'מטרות',
    'missions.objectivesPlaceholder': 'תאר את מטרות המשימה...',
    'missions.geoArea': 'אזור גיאוגרפי',
    'missions.startDate': 'תאריך התחלה',
    'missions.cancel': 'ביטול',
    'missions.create': 'צור משימה',
    'missions.drawPromptEmpty': 'לחץ על המפה כדי למקם קודקודי מצולע',
    'missions.drawPromptFew': 'נקודות סומנו – צריך לפחות 3 למצולע',
    'missions.drawPromptReady': 'נקודות – המצולע מוכן',
    'missions.undo': 'ביטול',
    'missions.clear': 'נקה',

    // Visitors
    'visitors.title': 'ניהול מבקרים',
    'visitors.subtitle': 'מעקב וניהול סינון אוכלוסייה',
    'visitors.newIntake': 'קליטה חדשה',
    'visitors.total': 'סה"כ',
    'visitors.cleared': 'אושרו',
    'visitors.observation': 'תחת מעקב',
    'visitors.flagged': 'מסומנים',
    'visitors.search': 'חפש לפי שם, ת.ז. או טלפון...',
    'visitors.allStatus': 'כל הסטטוסים',
    'visitors.underObservation': 'תחת מעקב',
    'visitors.name': 'שם',
    'visitors.idNumber': 'מספר זהות',
    'visitors.exposure': 'חשיפה',
    'visitors.status': 'סטטוס',
    'visitors.locations': 'מיקומים',
    'visitors.view': 'צפה',

    // Visitor Intake
    'intake.title': 'קליטת מבקר',
    'intake.subtitle': 'רשום מבקר חדש לסינון',
    'intake.personalDetails': 'פרטים אישיים',
    'intake.fullName': 'שם מלא',
    'intake.idNumber': 'מספר זהות',
    'intake.age': 'גיל',
    'intake.contact': 'טלפון',
    'intake.physicalMeasurements': 'מדידות פיזיות',
    'intake.exposureReading': 'קריאת חשיפה (μSv/h)',
    'intake.bloodPressure': 'לחץ דם',
    'intake.heartRate': 'דופק (פעימות/דקה)',
    'intake.temperature': 'טמפרטורה (°C)',
    'intake.visitedLocations': 'מיקומים שבוקרו',
    'intake.locationPlaceholder': 'שם מיקום או כתובת',
    'intake.addLocation': 'הוסף מיקום',
    'intake.notes': 'הערות',
    'intake.notesPlaceholder': 'תצפיות נוספות, תסמינים, היסטוריה רפואית...',
    'intake.register': 'רשום מבקר',
    'intake.registered': 'המבקר נרשם',
    'intake.registeredDesc': 'רשומת הקליטה נשמרה בהצלחה.',
    'intake.registerAnother': 'רשום מבקר נוסף',
    'intake.viewAll': 'צפה בכל המבקרים',
    'intake.bodyMeasurements': 'מדידות גוף',
    'intake.zonePlaceholder': 'אזור גוף (לדוגמה: ידיים, פנים)',
    'intake.addZone': 'הוסף אזור',
    'intake.removeZone': 'הסר אזור',
    'profile.bodyMeasurements': 'מדידות גוף',

    // Visitor Profile
    'profile.notFound': 'מבקר לא נמצא',
    'profile.notFoundDesc': 'רשומת המבקר לא אותרה.',
    'profile.backToVisitors': 'חזרה למבקרים',
    'profile.exportReport': 'ייצוא דוח',
    'profile.personalInfo': 'מידע אישי',
    'profile.measurementsSummary': 'סיכום מדידות',
    'profile.bloodPressure': 'לחץ דם',
    'profile.heartRate': 'דופק',
    'profile.temperature': 'טמפרטורה',
    'profile.movementPath': 'נתיב תנועה',
    'profile.start': 'התחלה',
    'profile.end': 'סיום',
    'profile.movementHistory': 'ציר זמן תנועה',

    // Analytics
    'analytics.title': 'ניתוח ודוחות',
    'analytics.subtitle': 'סקירה תפעולית וניתוח נתונים',
    'analytics.totalMeasurements': 'סה"כ מדידות',
    'analytics.activeMissions': 'משימות פעילות',
    'analytics.visitorsTracked': 'מבקרים במעקב',
    'analytics.teamsDeployed': 'צוותות בשטח',
    'analytics.criticalAlerts': 'התראות קריטיות',
    'analytics.today': 'היום',
    'analytics.total': 'סה"כ',
    'analytics.severityDistribution': 'התפלגות חומרה',
    'analytics.measurementsByType': 'מדידות לפי סוג',
    'analytics.readings': 'קריאות',
    'analytics.teamActivity': 'פעילות צוותות',
    'analytics.members': 'חברים',
    'analytics.reports': 'דוחות',
    'analytics.lastReport': 'דוח אחרון',

    // Settings
    'settings.title': 'הגדרות',
    'settings.subtitle': 'העדפות מערכת ותצורה',
    'settings.appearance': 'מראה',
    'settings.theme': 'ערכת נושא',
    'settings.themeDesc': 'מעבר בין מצב בהיר לכהה',
    'settings.interfaceMode': 'מצב ממשק',
    'settings.desktop': 'שולחני',
    'settings.desktopDesc': 'לוח מחוונים מלא',
    'settings.tablet': 'טאבלט',
    'settings.tabletDesc': 'תצוגה מצומצמת',
    'settings.mobile': 'נייד',
    'settings.mobileDesc': 'מצב שטח',
    'settings.notifications': 'התראות',
    'settings.thresholdBreach': 'התראות חריגת סף',
    'settings.thresholdBreachDesc': 'הודע כאשר מדידות חורגות ממגבלות',
    'settings.teamSOS': 'אותות מצוקה',
    'settings.teamSOSDesc': 'הודעה מיידית על אותות מצוקה',
    'settings.newMeasurementReports': 'דוחות מדידה חדשים',
    'settings.newMeasurementReportsDesc': 'הודע על דוחות שטח נכנסים',
    'settings.missionStatusChanges': 'שינויי סטטוס משימות',
    'settings.missionStatusChangesDesc': 'עדכונים כאשר משימות משנות מצב',
    'settings.visitorFlagging': 'סימון מבקרים',
    'settings.visitorFlaggingDesc': 'התראה כאשר מבקרים מסומנים',
    'settings.userProfile': 'פרופיל משתמש',
    'settings.fullName': 'שם מלא',
    'settings.email': 'דוא"ל',
    'settings.systemInfo': 'מידע מערכת',
    'settings.version': 'גרסה',
    'settings.serverStatus': 'סטטוס שרת',
    'settings.operational': 'פעיל',
    'settings.lastUpdate': 'עדכון אחרון',
    'settings.activeSessions': 'חיבורים פעילים',
    'settings.dataRetention': 'שמירת נתונים',
    'settings.days': 'ימים',
    'settings.mapProvider': 'ספק מפות',

    // Common
    'common.actions': 'פעולות',
    'common.notes': 'הערות',
    'common.save': 'שמור',
    'common.cancel': 'ביטול',
    'common.close': 'סגור',
    'common.delete': 'מחק',
    'common.edit': 'ערוך',
    'common.back': 'חזרה',
    'common.status': 'סטטוס',
    'common.alerts': 'התראות',
  },
};

export function LangProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Lang>(() => {
    const stored = typeof window !== 'undefined' ? localStorage.getItem('ecms-lang') : null;
    return (stored === 'he' ? 'he' : 'en') as Lang;
  });

  const setLang = useCallback((l: Lang) => setLangState(l), []);

  useEffect(() => {
    localStorage.setItem('ecms-lang', lang);
    document.documentElement.lang = lang;
    document.documentElement.dir = lang === 'he' ? 'rtl' : 'ltr';
  }, [lang]);

  const t = useCallback(
    (key: string) => translations[lang][key] ?? translations.en[key] ?? key,
    [lang],
  );

  const dir = lang === 'he' ? 'rtl' : 'ltr';

  return (
    <LangContext.Provider value={{ lang, setLang, t, dir }}>
      {children}
    </LangContext.Provider>
  );
}

export const useLang = () => useContext(LangContext);
